### ISSUE TITLE
Window counting doesn't work for two screens

### ISSUE THREAD

**Issue by splintersuidman** [splintah/blur#10]
`NumberOfWindowsOnSpace` actually counts windows on _visible_ spaces.

**Comment by asmvik** [comment]
This is how I do this in the *tiling* plugin:
https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/plugin.mm#L611

You won't be able to copy that exactly, but it could maybe give you a hint as of how you could try to implement this functionality.

**Comment by splintersuidman** [comment]
Thanks. I'll take a look.
