### ISSUE TITLE
Installation via homebrew

### ISSUE THREAD

**Issue by crisidev** [splintah/blur#11]
Hello,
I am maintaining chunkwm homebrew formula. I would like to add another formula for this plugin which flawlessly integrates with chunkwm master one. 

Would you consider this as something you want or are you ok with current distribution model?

**Comment by splintersuidman** [comment]
I would really like that!
I haven’t really thought about a distribution model, so it would be great if you would like to add a formula.

**Comment by crisidev** [comment]
So, if we want to do it, there are some modification needed to how you build and release things:
* A brew formula needs the source code and you depend on chunkwm header. Unfortunately your released package does not contain the checked out submodule for chunkwm, making the build impossible
* Your makefile is subshelling to pkg-config to get the MagickWand header and flags (https://github.com/splintah/blur/blob/master/makefile#L5). This is making the compilation very tricky since brew nukes your personal shell configurations and pkg-config is not found in the standard macosx path

Once these two issues are solved, I can make the formula.

**Comment by splintersuidman** [comment]
The first is fixed in `7bb0eaeb`, I believe (currently checked out at v0.3.0).
How would I go about fixing the second?

**Comment by crisidev** [comment]
I am not 100% sure, but one initial idea could be 

```
export PATH := /usr/local/bin:$(PATH)
```

on the top of your makefile. This will include the path where brew install imagemagick and pkg-config

**Comment by crisidev** [comment]
Regarding 1) the chunkwm code need to be inside the released tar.gz, like inside this one: https://github.com/splintah/blur/archive/v0.2.0.tar.gz

Version 0.3.0 is not released yet.

**Comment by splintersuidman** [comment]
> Regarding 1) the chunkwm code need to be inside the released tar.gz, like inside this one: https://github.com/splintah/blur/archive/v0.2.0.tar.gz
> 
> Version 0.3.0 is not released yet.

I meant chunkwm v0.3.0. It is added as a submodule to this repo, but when downloading the tarball, only the folder – pointing to the chunkwm repo – is downloaded. According to [this answer on StackOverflow](https://stackoverflow.com/questions/34719785/how-to-add-submodule-files-to-a-github-release#34721233) it is not possible to bundle the code from that repo in the tarball (unless, of course, you just clone the repo inside your own repo, which I don't want to).

Isn't it possible to make brew do something like `system "git", "submodule", "update", "--init", "recursive"` (I don't know Ruby works, only looked at the chunkwm formula)?

**Comment by crisidev** [comment]
It is not possible because the tarball you are releasing does not contain any .git folder. It contains only files know to the git repo, but not the repo itself, which makes sense since it is a release. 

Either you find a way to distribute the chunkwm headers needed from your repository (without using submodules) or this plugin will have to be built only from HEAD.

Any news about 2)?

**Comment by splintersuidman** [comment]
Hmm...
I really don't like to contain the chunkwm headers in this repo. Building from HEAD is the best solution then, I think.

No news yet about 2, I will _now_ take a look.

**Comment by crisidev** [comment]
Oook :) as you wish.

**Comment by splintersuidman** [comment]
If I add `export PATH := /usr/local/bin:$(PATH)` atop of the `Makefile`, and run `PATH=/usr/bin:/bin`, it compiles correctly. So: I think that should work.

**Comment by crisidev** [comment]
Ok, let me try the formula!

**Comment by crisidev** [comment]
Here is the new formula: https://github.com/crisidev/homebrew-chunkwm/blob/master/chunkwm-blur.rb

**Comment by crisidev** [comment]
To install:

```
brew tap crisidev/homebrew-chunkwm
brew install chunkwm-blur --HEAD
brew info chunkwm-blur
==> Caveats
The plugins install folder is /usr/local/opt/chunkwm-blur/share/chunkwm-blur/plugins

To activate the plugin, edit your ~/.chunkwmrc and add this load line:
  chunkc core::load /usr/local/opt/chunkwm-blur/share/chunkwm-blur/plugins/blur.so

Unfortunately since formulas are standalone in brew, we cannot just use chunkwm
standard plugin dir.

Given the dependency on chunkwm headers to build this plugin, the formula is HEAD only.
```

**Comment by splintersuidman** [comment]
Okay, cool! I'm going to update the README to describe this installation method.

**Comment by asmvik** [comment]
Just to chime in here a bit. The current way chunkwm works is mostly targetted to make my own development as easy as possible.

The current versioning is kinda "meh" from an external developers point of view.

Ideally, the header files should be versioned and any new plugins should copy the headers for the respective version they are targetting into its local repository. 

The code in */common/* should be provided (by me) as a compiled shared library that can be statically linked against (statically due to potential different versions required by different plugins).

From what I've seen the interest from others in developing plugins just hasn't really been there, so this is not something I've prioritized doing.

**Comment by splintersuidman** [comment]
Sounds like a good idea – once chunkwm is 'mature' enough.
