### ISSUE TITLE
Fails to set wallpaper if it was a Solid Color

### ISSUE THREAD

**Issue by dominiklohmann** [splintah/blur#8]
First of all: Nice plugin, I can see myself using this when it becomes a bit smoother. 👍 

Your method to set a wallpaper fails silently if the wallpaper set in System Preferences was a Solid Color (as shown below). 

<img width="780" alt="screen shot 2017-10-12 at 05 19 34" src="https://user-images.githubusercontent.com/4488655/31477657-f58c69d8-af0c-11e7-81b6-da3bfcab322a.png">

**Comment by splintersuidman** [comment]
Thanks! This isn’t meant to be a stable release yet, hence the 0.x.x versions. I’m trying to make it as smooth as possible.

Thanks for your bug report. I’ll look into it.
